version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app:latest
    container_name: modbus_51012799_sensor_meter_01
    env_file:
      - .env 
    restart: on-failure

  mongodb:
    container_name: database_mongodb_28000
    image: mongo:8.0.3
    restart: always
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    ports:
      - "28000:27017"
    volumes:
      - mongodb_28000:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file: .env

volumes:
  mongodb_28000: