version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app:latest
    container_name: modbus_51012799_sensor_meter_01
    env_file:
      - .env 
    restart: on-failure

  database:
    image: mongo:8.0.3
    container_name: database_mongodb_28000
    restart: always
    ports:
      - 28000:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pnevadmin
      - MONGO_INITDB_ROOT_PASSWORD=pca@1234
    volumes:
      - mongodb_28000:/data/db

volumes:
  mongodb_28000: 