version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app:latest
    container_name: modbus_51012799_sensor_meter_01
    environment:
      DEVICE_SETTING_URL: https://platform.planet-ev.com:8443/modbus/device/51012799/sensor_meter_01/deviceSetting.json
      MQTT_BROKER_URL: tcp://api.planetcloud.cloud:1888
      MQTT_USERNAME: admin
      MQTT_PASSWORD: pca@1234
      MONGODB_URL: database_mongodb_28000
      MONGODB_PORT: 27017
      MONGODB_USERNAME: pnevapp
      MONGODB_PASSWORD: pca1234
      MONGODB_DB_NAME: iot
    restart: on-failure

  mongodb:
    container_name: database_mongodb_28000
    image: mongo:8.0.3
    restart: always
    command:
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: pnevadmin
      MONGO_INITDB_ROOT_PASSWORD: pca1234
      MONGO_INITDB_DATABASE: iot
    ports:
      - "28000:27017"
    volumes:
      - mongodb_28000:/data/db
      - mongodb_28000_log:/var/log/mongodb/
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_28000:
  mongodb_28000_log: